services:
  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "5001:5000"
    environment:
      # 將 Ollama 服務的位址傳遞給您的應用程式
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped